import React, { useState, useEffect } from 'react'
import Head from 'next/head'

import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Address() {
     const [latitude, setLatitude] = useState("")
     const [getLocBool,setLocBool]=useState(false)
     const [longitude, setLongitude] = useState("")
     const handleLocationButtonClick=()=>{
          setLocBool(!getLocBool)
     }
     useEffect(() => {
          navigator.geolocation.getCurrentPosition(function (position) {
               setLatitude(position.coords.latitude)
               setLongitude(position.coords.longitude)
               console.log("Latitude is :", position.coords.latitude);
               console.log("Longitude is :", position.coords.longitude);
          });
     },[getLocBool])
     return (
          <>
               <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>
               <main className='p-4'>
                    <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold p-3 rounded-full mt-3 mb-3' onClick={()=>{
                         handleLocationButtonClick()
                    }}>Get Location</button>
                    <div className='font-bold text-2xl p-4'>
                    {getLocBool?(<><p>Latitude - {latitude}</p>
                    <p>Longitude - {longitude}</p></>):(<><p>Search for restaurants near your Location</p></>)}
                    </div>
               </main>
          </>
     )
}